### ISSUE TITLE
Autoload mission brief issue

### ISSUE THREAD

**Issue by MattCFII** [BeamRider/VRK-Releases#11] opened 2020-05-02 11:48 UTC
I have an issue with getting the autoload mission briefing tab to come up.  I've been able to consistently replicate it.  I can get it to load if I quit a mission and then hit fly again.  It is not just loading the previous mission brief because if I switch missions the previous mission brief does not come up.  If I hit "close" on mission and then reload that same mission and enter it the briefing will not be there.  So I basically have to enter a mission, "quit" and then "Fly Again" to update the tab. 
My VrkGameGui.lua version line is "VRK - Startup v1.0.3.8"

**Comment by BeamRider** [comment] 2020-06-28 15:09
I'm trying to reproduce this issue but the eaxt procedure is not clear.
Can you list a sequence of steps and expceted/obtained result?

**Comment by MattCFII** [comment] 2020-06-28 15:22
This is for single player missions, have not tested for multiplayer.  When I get into the cockpit of any mission, the mission brief autotab and now scratchpad tab do not show up.  Exiting the mission and selecting even that same mission or another mission will not not get the autoload tabs to populate.  The only way to get those tabs to come up on my system through multiple versions of both VRK and DCS (but not the open beta) is to exit the cockpit and and hit "Fly Again".  The scratchpad tab will also keep up with changes at that point.

Matt (Snake122 on discord/DCS forums)

**Comment by BeamRider** [comment] 2020-06-28 15:56
For the scratchpad check if they are enabled in the options, under DCS.

I will contact you via Discord to collect some relevant files.

**Comment by MattCFII** [comment] 2020-07-22 13:26
I've noticed that if I do missions created in Mission Builder instead of the premade/bought campaigns that the odds of the mission brief autoloading is greater but still not 100%

**Comment by BeamRider** [comment] 2020-08-27 16:02
The problem is due to DCS behavior in loading campaign/module missions. The first time the reported miz path is relative to DCS installation directory, if you "Fly Again" then the path is absolute to a temporary miz file.

Fix is under test.

**Comment by MattCFII** [comment] 2020-08-27 16:49
Awesome, will test when you release!

**Comment by BeamRider** [comment] 2020-08-31 09:59
Fix has been implemented and delivered in the 1.4.2.01 test version available on Discord.
Can you check it?

**Comment by BeamRider** [comment] 2020-09-20 11:34
Released on v1.4.3.07

**Closed by BeamRider** 2020-09-20 11:34 UTC
Labels: bug
