### ISSUE TITLE
Flickering KBs and pen registration issues

### ISSUE THREAD

**Issue by Nagilem** [BeamRider/VRK-Releases#14] opened 2020-06-07 03:33 UTC
Rider -

Seems like the latest update has made the kneeboards a bit unpredictable. My KBs flicker alot - they will go focused and unfocused, and worse, they will disappear if Itry to use the pen. Very hard to write on something that keeps disappearing. Also, the pen registration over the digitizer also is spotty. It registers with the cross about 60% of the time. I have to actually write something to get it to recognize the pen at times. 

Any thoughts on how I can fix these?

**Comment by BeamRider** [comment] 2020-06-28 13:29
Flickering is caused by HW acceleration in combination with SteamVR. The root cause is due to some synchronization missing between texture generation of VRK content and SteamVR presentation. The more updates are generated (i.e. pen tracing strokes or just moving) the more likely the flickering happens.

**Comment by BeamRider** [comment] 2020-06-28 15:53
This should have been fixed in public version 1.3.3.22

**Comment by Nagilem** [comment] 2020-06-29 14:33
Perfect – Thank you sir. Love the app!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Closed** 2020-07-02 12:38 UTC
