### ISSUE TITLE
VRK Stops working in VR after change is made on desktop 

### ISSUE THREAD

**Issue by ShortyJSW** [BeamRider/VRK-Releases#8] opened 2020-04-28 18:55 UTC
When I make a change on the desktop, The VR kneeboards go dim and no changes made on the desktop are reflected in the VR image.

When I use the pen or buttons for example, they work on the desktop but have no effect on the VR image.

In the log I have attached the changes I made were to change some input keys.
[vrk.log](https://github.com/BeamRider/VRK-Releases/files/4547919/vrk.log)

**Comment by BeamRider** [comment] 2020-06-02 11:04
This problem seem correlated with Wacom driver removing the device from VRK control.

Some questions:

1. Is your pen tablet connected via USB or Bletooth? 
2. Can you add your a Wacom Tablet Properies screenshot?
3. Does this happen every time you switch from the simulator to another window or when you play with VRK with the mouse?
4. Can you add a desktop screenshot?

**Comment by BeamRider** [comment] 2020-08-27 16:05
Can you check if problem is still present in version 1.3.3.22 ?

**Comment by BeamRider** [comment] 2020-09-20 11:39
Closing because I was unable to reproduce. If this issue is still there, please reopen it.

**Closed by BeamRider** 2020-09-20 11:39 UTC
